import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <a
          href="https://exoplanets123.netlify.app"
          className={cn(buttonVariants(), "absolute top-[10px] right-[10px] font-mono")}
          target="_blank"
        >
          View Exoplanets
        </a>
        {children}
      </body>
    </html>
  );
}
